### ISSUE TITLE
'Flowchart' connector: loopback connections broken

### ISSUE THREAD

**Issue by daskyrk** [sporritt/jsPlumb#457] opened 2015-11-30 09:08 UTC
*  In the demo 'statemachine',i want to **change the connectorType from 'StateMachine' to 'Flowchart'** as the code below:
```
var instance = jsPlumb.getInstance({
        Endpoint: ["Dot", {radius: 2}],
        Connector:"Flowchart",//here,change from StateMachine to Flowchart
        ...
    });
```
**an error will occured:**

```
Error: Invalid value for <path> attribute d="M 463 144 L 431 144 M 432 145 L 432 NaN M 433 NaN L 29 NaN M 30 NaN L 30 -1 M 30 0 L 0 0 "
```

---
*  if i **use the function 'registerConnectionType' rather than use the default 'Connector' attribute**,it will not work,which means the connectionType is still 'StateMachine'
```
instance.registerConnectionType("basic", { anchor:"Continuous", connector:"Flowchart" });
```

---
*  so i try to add the attribute 'connector' in this way:
```
instance.makeSource(el, {
            filter: ".ep",
            anchor: "Continuous",
            connector:  "Flowchart",// add this line
            connectorStyle: { strokeStyle: "#5c96bc", lineWidth: 2, outlineColor: "transparent", outlineWidth: 4 },
            //connectionType:"basic",//comment this line
            ...
        });
```
the connectionType changed,but when i connect a window to itself,**an error will occured like before:**
```
Error: Invalid value for <path> attribute d="M 156.5 60 L 124.5 60 M 125.5 61 L 125.5 NaN M 126.5 NaN L 29 NaN M 30 NaN L 30 -1 M 30 0 L 0 0 "
```

is there any bug here or just i use it in the wrong way?

**Comment by sporritt** [comment] 2015-11-30 19:09
Are you doing this with the 2.1.0 development version?

**Comment by daskyrk** [comment] 2015-12-01 00:09
no,with the version 2.0.4 final, i'll have a try on 2.1.0,thx.

2015-12-01 

daskyrk 



发件人：Simon Porritt <notifications@github.com>
发送时间：2015-12-01 03:09
主题：Re: [jsPlumb] in demo 'statemachine' when default connector is 'Flowchart' error occured (#457)
收件人："sporritt/jsPlumb"<jsPlumb@noreply.github.com>
抄送："随风"<daskyrk@163.com>

Are you doing this with the 2.1.0 development version?

**Comment by daskyrk** [comment] 2015-12-01 01:51
I have tried on version 2.1.0,it still have the problem.

**Comment by sporritt** [comment] 2015-12-01 02:22
i asked about 2.1.0 because there's a bunch of code in that demo right now that probably would mean it wouldnt work.  i think perhaps this is a bug with that connector, potentially.  i will take a look.

**Comment by sporritt** [comment] 2015-12-13 01:26
this is a defect in the Flowchart connector. targeting 2.1.0.

**Comment by sporritt** [comment] 2015-12-14 01:29
@daskyrk the flowchart connector has never actually been configured to paint itself properly when it should draw a loop; you're the first person to try this. so the fix for this was to implement that:

![image](https://cloud.githubusercontent.com/assets/262720/11770954/1151835a-a25e-11e5-8416-852fc2ed3b3c.png)


this is in 2.1.0 dev now. i am in fact going to release version 2.0.5 next, since i have a few bugfixes i want to get out and i havent finished the feature that would warrant bumping the minor version up to 2.1.x, so the fix for this will be in 2.0.5. should be released in the next couple of days.

**Closed** 2015-12-14 02:54 UTC
Labels: defect

**Comment by crazyvonni** [comment] 2016-07-07 15:15
Sorry, but this issue is still not fixed for me. I use version 2.1.4 and get still the same error like in the first post. 

The if in line 183 in src/connectors-flowchart.js (in the last mentioned fix) is never true for me - although source and target node are equal (loopback). 

`Error: jsPlumb-2.1.4.js:6411 Error: <path> attribute d: Expected number, "M 0 -5 L NaN NaN MNaN NaN…".`

If I change the line 183 to the following,  it is fixed but the "arrow" is misplaced. 
`if (params.sourceEndpoint.elementId == params.targetEndpoint.elementId) {`

This issue only happens for connection which are created at the beginning with "instance.connect" in the "instance.batch" function. If I do a loopback manually, everything is fine. I work with "makeSource" and "makeTarget" and "anchor: 'Continuous'". 

![jsplumb](https://cloud.githubusercontent.com/assets/3245822/16658256/fb80aa74-4465-11e6-8f78-a5eaf92c1617.png)

Loopback on Vehicle is done on startup (with my fix), loopback on Site is done manually.

**Comment by sporritt** [comment] 2016-07-07 23:23
can you provide a jsfiddle?

**Comment by crazyvonni** [comment] 2016-07-08 08:22
Yes, sure: 
http://jsfiddle.net/Vonni/rpnxk8ty/

I think, I have found the cause: 
`  instance.registerConnectionType("basic", {`
`//    anchor: "Continuous",`
`    connector: "StateMachine"`
`  });`

If there is no "anchor" definition in "registerConnectionType", the loopback connections will fail.
