### ISSUE TITLE
style set incorrectly when adding to Group

### ISSUE THREAD

**Issue by saiprashanths** [sporritt/jsPlumb#547] opened 2016-08-17 09:00 UTC
It looks like a node's style properties (`top` and `left`) are incorrectly set when it is dragged and dropped onto a Group. I am obtaining the style props after a drag event using the code below. 

```javascript
this.instance.draggable(nodeId, {
  start: () => {
	// console.log('Starting to drag');
  },
  stop: (dragEndEvent) => {
	  style: {
		top: dragEndEvent.el.style.top,
		left: dragEndEvent.el.style.left,
	  },
	  console.log('Position: ', style);
  },
});
```

When a node is dragged and dropped onto the plain canvas its position is say {top: 50px, left: 50px}. However, when the same node is dragged and dropped onto a Group in the same absolute location, its position is set to something very different, say {top: 20px, left: 25px}. What could be the cause of the discrepancy?

**Comment by saiprashanths** [comment] 2016-08-17 09:29
Ok, I figured it out. Looks like the member's style is relative to the Group... makes sense.

So, when the Group is deleted without deleting its members (using `jsPlumb.removeGroup("aGroup", false)`), it messes up the position of the member. To fix this, one has to recompute the absolute position of the member. This can be done by adding the absolute position of the Group (before it is deleted) to the relative position of the member within the Group.

**Comment by sporritt** [comment] 2016-08-17 10:35
But maybe the fact that the child node positions are not recomputed could be considered a bug?

**Comment by saiprashanths** [comment] 2016-08-17 10:48
Yes, it looks like a bug and what I have is only a workaround.

**Comment by sporritt** [comment] 2016-08-18 04:19
i wrote a unit test for this which succeeds: child positions are adjusted. and also on this demo, try removing the group at the bottom right:

https://jsplumbtoolkit.com/community/demo/groups/index.html

so i'm unable to reproduce the issue right now. can you try recreating in a jsfiddle?

**Comment by sporritt** [comment] 2016-08-18 04:36
i cannot reproduce this, in a unit test or on this demo

https://jsplumbtoolkit.com/community/demo/groups/index.html

(try deleting the bottom right group)

if you are still having issues can you reproduce in a fiddle? and maybe change the title of the issue.

**Comment by sporritt** [comment] 2016-09-04 14:03
closing due to inability to reproduce. if you can reproduce it we can re-open and take a look.

**Closed by sporritt** 2016-09-04 14:03 UTC
