### ISSUE TITLE
setSourceEnabled method not working

### ISSUE THREAD

**Issue by lunij** [sporritt/jsPlumb#517] opened 2016-04-12 23:30 UTC
```coffeescript
jsPlumb.on '.foobar', 'click', (event) ->
    jsPlumb.setSourceEnabled(this, false)
    jsPlumb.setTargetEnabled(this, false)
```

I expect this coffeescript code to apply a click handler on all DOM elements with the class 'foobar' and when the event was triggered the underlaying element should be disabled for connection creation (drawing included).

Am I wrong? If not, then both methods do not work with version 2.0.7.

**Comment by sporritt** [comment] 2016-04-13 05:14
you can't pass a selector as the first argument to jsPlumb's `on` method. you need to provide it an element or a list of elements.

**Comment by lunij** [comment] 2016-04-13 20:34
Really interesting reading this from you.

```
jsPlumb.on '.foobar', 'click', (event) ->
    event.preventDefault()
    console.log('clicked')
    console.log(this)
    jsPlumb.setSourceEnabled(this, false)
    jsPlumb.setTargetEnabled(this, false)
```

Both `console.log()` calls are triggered in my case.

**Comment by sporritt** [comment] 2016-04-13 20:39
Really interesting reading that too.

**Comment by sporritt** [comment] 2016-04-13 20:40
Can you provide a jsFiddle?

**Comment by lunij** [comment] 2016-04-13 20:42
The following provides the same behavior, except of the jQuery reference `$(this)`.

```coffeescript
$('body').on 'click', '.foobar', (event) ->
    console.log('clicked')
    console.log($(this))
    jsPlumb.setSourceEnabled($(this), false)
    jsPlumb.setTargetEnabled($(this), false)
```

**Comment by sporritt** [comment] 2016-04-13 21:05
I think it's cool that jsPlumb supports a selector as the first argument. Every now and then i am reminded that the API has grown to a size where i cant remember the whole thing in my head anymore.

A jsFiddle would be useful so i can see exactly what is going on in your case.

**Comment by lunij** [comment] 2016-04-13 21:22
http://codepen.io/lunij/pen/ONvgOR

Something in the Codepen is still missing, because a double-click inside the canvas adds a new node in html but it's not visually visible.

jsFiddle is disconnecting the network connection for me today, so it doesn't save the fiddle properly.

**Comment by lunij** [comment] 2016-04-14 21:29
I've edited the CodePen. The click event doesn't get triggered like `jsPlumb.on '.foobar'` but with the jQuery way it is working properly. Btw this is only for the click event. `jsPlumb.on '.foobar', 'contextmenu'` gets triggered.

Anyway, the actual issue is the `jsPlumb.setSourceEnabled()` method. In the CodePen, a right-click on the canvas div toggles draggable, so you can create connections without moving the nodes. With an additional click on a node and the following `setSourceEnabled(this, false)`, I expect to not be able to create a connection from the exact same node. But it's still possible. `jsPlumb.isSourceEnabled(this)` has also a wierd behavior, because it always returns `undefined`.

**Comment by sporritt** [comment] 2016-04-15 01:11
this issue is a duplicate of a previous issue:

https://github.com/sporritt/jsPlumb/issues/466



the person who filed that issue report identified what has changed: in 2.0.x, a single element may be the source for a number of different connection types.

```
this.setSourceEnabled = function (el, state, connectionType) {

}
```

in that codepen there were a couple of issue - i removed the `draggable` call since i did not find it possible to drag connections, and there was a jsplumb context menu listener that was actually consuming the event, so the jquery context menu listener was not being fired. i removed that one too anyway, since you also had a click listener.

ultimately nothing was going to work for you though since you were calling `jsPlumb.setSourceEnabled` when you had made all your connections with `instance`, a different instance of jsPlumb. so i changed that too.

the coffee script code looks like this now and after a click connections are disabled:

```
jsPlumb.ready ->

  instance = jsPlumb.getInstance(
    Endpoint: [ 'Dot', { radius: 2 } ]
    Connector: 'StateMachine'
    HoverPaintStyle:
      strokeStyle: '#1e8151'
      lineWidth: 2
    ConnectionOverlays: [
      [
        'Arrow'
        {
          location: 1
          id: 'arrow'
          length: 14
          foldback: 0.8
        }
      ]
    ]
    Container: 'canvas'
  )

  instance.registerConnectionType 'basic',
    anchor: 'Continuous'
    connector: 'StateMachine'

  window.jsp = instance
  canvas = document.getElementById('canvas')
  windows = jsPlumb.getSelector('.statemachine .w')

  jsPlumb.on canvas, 'dblclick', (event) ->
    event.preventDefault()
    console.log('canvas dblclick')
    newNode event.offsetX, event.offsetY

  # jsPlumb.on '.w', 'click', (event) ->
  #   event.preventDefault()
  #   console.log('.w click')
  #   jsPlumb.setSourceEnabled(this, false)
  #   jsPlumb.setTargetEnabled(this, false)
    
  # jsPlumb.on '.w', 'contextmenu', (event) ->
  #   event.preventDefault()
  #   console.log('.w contextmenu')
  #   jsPlumb.setSourceEnabled(this, false)
  #   jsPlumb.setTargetEnabled(this, false)
    
  $('#canvas').on 'click', '.w', (event) ->
    event.preventDefault()
    console.log('jquery click')
    instance.setSourceEnabled(this, false, 'basic')
    instance.setTargetEnabled(this, false, 'basic')
   

  initNode = (el) ->
    instance.makeSource el,
      anchor: 'Continuous'
      connectorStyle:
        strokeStyle: '#5c96bc'
        lineWidth: 2
        outlineColor: 'transparent'
        outlineWidth: 4
      connectionType: 'basic'
      extract: action: 'the-action'
    instance.makeTarget el,
      dropOptions: hoverClass: 'drag-hover'
      anchor: 'Continuous'
      allowLoopback: true
    instance.fire 'jsPlumbDemoNodeAdded', el
    return

  newNode = (x, y) ->
    d = document.createElement('div')
    id = jsPlumbUtil.uuid()
    d.className = 'w'
    d.id = id
    d.innerHTML = id.substring(0, 7)
    d.style.left = x + 'px'
    d.style.top = y + 'px'
    instance.getContainer().appendChild d
    initNode d
    d

  instance.batch ->
    i = 0
    while i < windows.length
      initNode windows[i], true
      i++
    return
  jsPlumb.fire 'jsPlumbDemoLoaded', instance
  return
```

**Comment by sporritt** [comment] 2016-05-14 00:33
Closing. Solution provided.

**Closed by sporritt** 2016-05-14 00:33 UTC
