### ISSUE TITLE
ZoomIn and Out limitations due to container based zoom

### ISSUE THREAD

**Issue by Deklin** [sporritt/jsPlumb#304] opened 2014-12-15 20:26 UTC
With the current zoomin/out technique of zooming the container, this means that the container dimensions are also shrinking when you apply the zoom out, and expanding on a zoom in.

I believe the goal of zooming out should be to shrink the nodes down so you can see more of them on the screen at once, however this goal can't be accomplished with a container level zoom. since the entire container shrinks. Same for the reverse, the container grows and you lose your scroll bars (they go off screen)

This seems an issue to me, if there is a workaround or some other way to accomplish this please let me know
Thanks

**Comment by sporritt** [comment] 2015-01-01 12:53
in the absence of a follow up i'm closing this out.

**Closed by sporritt** 2015-01-01 12:53 UTC

**Comment by Deklin** [comment] 2015-01-02 00:12
I'll reopen I've been on vacation and away from my computer so I haven't
been able to create you the fiddle yet

**Comment by sporritt** [comment] 2015-01-02 00:29
maybe you can use this one from another issue as a reference

http://jsfiddle.net/uyhu2akd/15/

(from #308 )

**Comment by flooie** [comment] 2017-05-01 02:43
I also have been having the same issue.

**Comment by sporritt** [comment] 2017-05-01 05:46
the last activity on this issue was me requesting a fiddle demonstrating the problem. do you have one?

**Comment by flooie** [comment] 2017-05-01 12:41
Not yet, but I can share with you what I and I believe @deklin was saying.  

<img width="1212" alt="screen shot 2017-05-01 at 8 40 19 am" src="https://cloud.githubusercontent.com/assets/6464529/25579890/f1926772-2e49-11e7-98ac-879e26507a0b.png">
<img width="1200" alt="screen shot 2017-05-01 at 8 40 45 am" src="https://cloud.githubusercontent.com/assets/6464529/25579891/f1982950-2e49-11e7-9ed4-d9b2bbf34b7f.png">

**Comment by sporritt** [comment] 2017-05-01 12:45
i dont see that there is any problem at all. Have you seen any of the Toolkit edition demos?

**Comment by flooie** [comment] 2017-05-01 12:48
Unfortunately I am working only in community edition.  And the problem is that

**Comment by sporritt** [comment] 2017-05-01 12:52
I'm asking if you've seen the Toolkit demos because the Toolkit uses the Community edition's zoom, with the container inside another element as mentioned above. I could never really see what the problem was that @Deklin was having.  When you zoom out things get smaller? Ok, great!  etc.

**Comment by flooie** [comment] 2017-05-01 12:57
Any chance you could link to the demo you are referring.  I haven't found one that matches.

**Comment by sporritt** [comment] 2017-05-01 13:05
every single Toolkit demo has zoom. the ones on the home page have it.  https://jsplumbtoolkit.com

**Comment by flooie** [comment] 2017-05-01 13:26
Thanks for the pointers sporritt

**Comment by sporritt** [comment] 2017-05-01 13:29
No problem.
