### ISSUE TITLE
Cannot drag on touchscreen monitors

### ISSUE THREAD

**Issue by slandmann** [sporritt/jsPlumb#325] opened 2015-02-19 18:18 UTC
Hi,

I cannot drag using the mouse on laptop with a touchscreen. This occurs in my project as well as the jsplumb demo. Is there a fix for this?

**Comment by sporritt** [comment] 2015-02-19 22:32
@slandmann is this on jquery or vanilla jsplumb?

**Comment by slandmann** [comment] 2015-02-26 22:25
It seems to be an issue on vanilla jsplumb as I can drag around using jquery's draggable example without any issues on the same system. Any ideas? Thanks in advance.

**Comment by sporritt** [comment] 2015-02-27 01:38
without a jsfiddle and some more information about hardware, no.

**Comment by sporritt** [comment] 2015-03-03 01:52
adding to 1.7.4 milestone just for tracking...without more information i can't do anything about this right now.

**Comment by sporritt** [comment] 2015-03-04 12:14
closing this because there are no details.  seems possible it is a duplicate of #295.

**Closed by sporritt** 2015-03-04 12:14 UTC

**Comment by sporritt** [comment] 2015-03-20 12:15
..and 295 is fixed in 1.7.5 dev, so this likely is too.
